apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "root"
        - name: MARIADB_DATABASE
          value: "indoor_atmosphere_control"
        - name: MARIADB_USER
          value: "user"
        - name: MARIADB_PASSWORD
          value: "passwd"
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: mariadb-volume
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
      volumes:
      - name: mariadb-volume
        configMap:
          name: mariadb-config